version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_heimdall
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: heimdall_user
      POSTGRES_PASSWORD: heimdall_pass
      POSTGRES_DB: heimdall_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nest_heimdall
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "start:dev"]

volumes:
  postgres_data:
